### ISSUE TITLE
Menu doesn't appear when using a bottom panel

### ISSUE THREAD

**Issue by Pointedstick** [Maestroschan/emoji-selector-for-gnome#1]
I use the dash-to-panel extension and have my panel on the bottom of the screen. The emoji-selector menu does not appear to select it, as the menu doesn't appear when clicked. The menu always draws *below* the icon, not above it if necessary.

**Comment by Maestroschan** [comment]
I think i understood what creates the problem : submenus are scrollable lists whose heights depend by default on your screen, and i guess that the "available height" parameter is changed by Dock To Panel, which makes these submenus unable to function well.
(the "Smileys & People" submenu is supposed to be open by default when you open the menu. When I desactivate this behavior, the menu appears but submenus are unable to expand, so it still don't work but it means submenus'heights are the problem)

It might be possible to solve the issue, i will try something

**Comment by Maestroschan** [comment]
Hi, I just made a new version of the extension. It not on the official gnome website yet but it's far better than my first try.
Thanks to your report, I also did a "dash to panel" version, where some minor changes allow my extension to work. This version is on this branch : https://github.com/Maestroschan/emoji-selector-for-gnome/tree/for-dash-to-panel
You can try to install it manually (see the README file), it should work ;)

**Comment by Pointedstick** [comment]
Thanks! I'm not using GNOME anymore so I'm not in a position to verify this (sadly, KDE Plasma doesn't have anything as good as this), so feel free to close the issue.
