### ISSUE TITLE
Instant search feature

### ISSUE THREAD

**Issue by orospakr** [Maestroschan/emoji-selector-for-gnome#10]
It would be awesome if there was an inline search box (akin to the emoji selection box available on OS X) for searching for emoji by name/keyword (you can already do this in Character Map).

Extra benefit this provides: you could use it to search for other special characters conveniently too, like °, ™ and so on.

Thank you!

**Comment by orospakr** [comment]
For reference, this is the OS X feature: http://osxdaily.com/2015/05/27/quick-type-emoji-mac-keyboard-shortcut/

**Comment by Maestroschan** [comment]
I like the idea (even if I just add a "set size" parameter, it's is sometimes still a pain in the ass to find a specific emoji), but it means the extension needs to know a big number of datas : 
- the name of each emoji (around 1500)
- with translation in each language (the extension is currently only available in french, german, portuguese, english and esperanto, i only maintain english and french)

For example, Gnome Shell is already able to search characters from Character Map (like this http://image.noelshack.com/fichiers/2017/18/1493632101-capture-d-ecran-de-2017-05-01-11-48-05.png i don't remember if it's a default behavior or if i set that) but even if my system is in french, i can't search characters from their french names : no one tried to fully translate characters names, even if it's a official Gnome application.

I'm quite unwilling to have a bunch 1500-entries-long .po files : it would mean i have to fill both the original .js file in english and the .po file for french (and it's not actually "translating", it's more "copy-paste each standard denomination from official Unicode CLDR annotations"), which is long and boring af, it would discourage both me and eventual translators.

I will try to implement this when i have a looooot of free time

**Comment by orospakr** [comment]
Hmmm as far as I can tell there's a Unicode database that you should be able to search (pretty sure that GNOME's Character Map utility is not using gettext for unicode character names).

When I have some free time I'll look into it ;)

**Comment by Maestroschan** [comment]
i began something (not on github yet)
http://i.imgur.com/l4ghO8e.png
it only search through "smileys and peoples" for now but it looks cool

**Comment by goncalossilva** [comment]
How's this going? Would love to have this feature, specially now that colored emojis are supported.

(A configurable keyboard shortcut to open up the extension would be great, too!)

**Comment by Maestroschan** [comment]
i still have a problem with the focus of the entry :(

however i will commit it here if some people want to test it

**Comment by Maestroschan** [comment]
I solved my problem, you can now test the beta if you want, the only thing which is broken is theorically the "food & drink" icon (which is easy to fix).

I will wait a few days before releasing it, until then i will try to understand how keyboard shortcut are supposed to work

**Comment by Maestroschan** [comment]
I didn't understand how to make it configurable so the keyboard shortcut is just <Super>e and you can't change it ;) (you actually can change it via dconf-editor but it's not very user-friendly)

So:
>Super e
>*typing things to search*
>press enter
>ctrl v

And you have your emoji!
It's not as good as a direct insertion, but it's a fluid, 100% keyboard, way to do.

You can also search "in a category only" if you want.

**Comment by amivaleo** [comment]
You can check how some other extension lets the user choose the shortcut.
Like in the clipboard-indicator: https://extensions.gnome.org/extension/779/clipboard-indicator/

**Comment by Maestroschan** [comment]
Yes this was my model to make the shorcut itself, but concerning the way they set the shortcut, i failed to reproduce it...

**Comment by stjepang** [comment]
Can we make the search box case-insensitive?

**Comment by Maestroschan** [comment]
of course, i will try this next month

**Comment by Maestroschan** [comment]
(in fact it's already done, it was easier than expected)

**Comment by Maestroschan** [comment]
>I'm quite unwilling to have a bunch 1500-entries-long .po files

ok lol, maybe i forgot i wrote that, and i added my scripts for automatically rebuilding translations files

![](https://i.imgur.com/XfqNjur.png)
