### ISSUE TITLE
GNOME-wide emojis

### ISSUE THREAD

**Issue by picsi** [Maestroschan/emoji-selector-for-gnome#11]
Not a proper bug, I just thought I'd show you this https://wiki.gnome.org/Design/OS/Emoji in case you haven't already seen it. It'd be great to have that as a less hacky solution for emojis on GNOME.

Feel free to close this :)

**Comment by Maestroschan** [comment]
There is even better ! https://fedoramagazine.org/using-favorite-emoji-fedora-25/
(i don't know if it exists in other distributions and with other keyboard layouts, but it would be great)
