### ISSUE TITLE
Some change in stylesheet.css

### ISSUE THREAD

**Issue by amivaleo** [Maestroschan/emoji-selector-for-gnome#13]
Hi!

I noticed that the hovered emoji is bolded. Because of this, its size becomes a bit bigger. It is not a pleasent effect in my opinion.
I tried to change the stylesheet.css file as the following:
```
.EmojisItemStyle {
    /*font-size: 20px; useless since it is now a setting*/
    font-family: EmojiOne Color, Twitter Color Emoji, Noto Color Emoji;
    padding: 4px;
}

.EmojisItemStyle:hover {
	background-color: rgba(0, 0, 0, 0.5);
	border-radius: 6px;
	padding: 4px;
}

.RecentItemStyle {
    font-size: 28px;
    font-family: EmojiOne Color, Twitter Color Emoji, Noto Color Emoji;
    padding: 4px;
}

.RecentItemStyle:hover {
	background-color: rgba(0, 0, 0, 0.5);
	border-radius: 6px;
    padding: 4px;
}
```

My opinion is that it makes the grid more "readable" and a bit nicer. It is just a matter of tastes, of course.
Give it a try, maybe you can enojy it too.

Thank you for your work on Gnome.
;)

**Comment by amivaleo** [comment]
I prefer squared buttons, that's why I put the same padding in both vertical and horizontal directions. And since I have a touchscreen that I use a lot, I increased the spacing between the icons: it is somewhat easier not to miss the right emoji with your finger.
I "hacked" your extension so that it is VERY big, as you can see from the attached file. I did this also because the icons have no color, so it is a bit hard for me to select the right one at a first glance (in a 13" screen at least).

So... It is up to you how you want to make it appear. If you accept suggestions: try to give the user all the freedom you can.
![schermata da 2017-05-02 15-21-56](https://cloud.githubusercontent.com/assets/24316547/25619440/28434a82-2f4b-11e7-8f7d-48095d6cdf2e.png)

**Comment by Maestroschan** [comment]
Squarred buttons are great, but there is already some vertical space between buttons : with smaller fonts it looks strange and not square at all (and users might need to scroll more).

(buttons are in BoxLayouts which are in some horizontal PopupBaseMenuItems, and these menu items have a style with a padding which is set by the shell theme i guess).

I didn't think about touch screens, i will set a higher limit to the font size setting.

**Comment by Maestroschan** [comment]
Concerning tabs, i don't know how to do because  when i see how it looks on your screen i understand the motivation, but it would mean that the popup **have to** use almost the whole screen width whatever are the user settings : it doesn't look like a very optimal interface to me

**Comment by amivaleo** [comment]
Yes, I noticed some vertical padding between consecutive rows. At the beginning I thought it was something that you put there, but I didn't find anything. Now I understand why. :D

I'm so annoying about the horizontal vs vertical tabs because I think that the best way to improve usability (of any interface) is to conform to the trends. It is not a bad thing: people expect to have a common user experience "everywhere".
In this case, I think people are used to the way android shows emojis:

![](https://cdn1.pcadvisor.co.uk/cmsdata/features/3633850/how-to-use-emoji-on-android_thumb800.jpg)

You have horizontal tabs on top, and each tab shows 4 rows of emojis at a time. Of course you can scroll vertically to see other emojis, but only 4 rows at once. It doesn't really matter that they are exactly 4, of course, the point is: this number is fixed for every tab.
I think that you could do something very similar, with a main difference: the first tab on android is for the most recent emojis. I'd stick to the way you decided to show those recent emojis: a single line on top of everything. I think you could also use a representative emoji instead of the terms "nature" / "flags" / "food" / etc, just like android does.

These are just ideas, of course. The way I hacked your extension satisfies MY personal needs, I do not expect that everybordy likes it, of course! :D But even if you stick to smaller emojis, I still think that a vertical list for the tabs is a waste of space, and also the user is somewhat forced to open the tabs from the last one (flags) to the first one if he doesn't want to move the mouse a lot.

Unfortunately I still can't program or I would have already done the facts by now, (1) because I'd like to have an emoji extension as I've just explained and (2) because I'd like to give some real help a part from ideas and translations.

I hope we (I should say "you devs") will find a way to have colorful emojis in this kind of extension. That would be very interesting.
:)

**Comment by Maestroschan** [comment]
Tabs with icons are an interesting way to do, i will try it when the "research" will be fonctionnal.

Concerning the "color" issue, this thing exists http://www.omgubuntu.co.uk/2016/02/emoji-picker-app-for-ubuntu-desktop (i've never tried but the screenshot shows colored emojis). They directly use image files from EmojiOne Color instead of displaying Unicode character. Maybe i will try to do something like this.

**Comment by amivaleo** [comment]
I tried it some time ago. I don't like it at all.
It shows a list of menus and a bunch of (vertical) sub-menus and so on. Very tiny icons, too much text. I'd never use such a thing. When I want to use emojis, I want them quickly.

I'm glad I could have at least given you some stimulating idea. :)
Thank you again for your work, I'll keep hacking it! :D

**Comment by Maestroschan** [comment]
Little update: i'm finally doing something serious on this extension https://i.imgur.com/UwmIcrN.png (it was my version with the unreleased research feature, and i changed it to use buttons).

- Concerning buttons, it's vaguely based on what you did, but all the CSS tweaks were not very coherent anymore when i tried other themes, so i use system menu buttons instead of custom tabs (i use some icons from /usr/share/icons/ because these buttons can't have an actual label)

- Concerning color emojis, i never succedeed to make your fork fully working on ALL categories... the 5 first are really amazing, but Objects, Symbols and Flags never worked, so i guess it's just too heavy in RAM (there is no warning in logs so i'm not sure, but it's 12Mo !). I read color emojis were natively supported in 3.26: if i can witness that, i will not try the CSS technique, since we can't upload Apple emojis on the gnome website under a GPLv2 license anyway.

**Comment by amivaleo** [comment]
Hi!

I'm sorry for the late reply.
You can look at my project here: https://github.com/amivaleo/Emojis
I managed to show coloured emojis, but I just used a trick... I wrote
hundreds of lines in the css file, each of which is for one single emoji.
It's just a trick, but it works. I'm quite sure that there's a way to make
it smarter.

I'm currently using my version of your extension, even if the buttons do
not work. I really have no clue on how to fix them. I'm totally ignorant on
js.

You state that "i never succedeed to make your fork fully working on ALL
categories", but what you get from my repo is what you see here:
[image: Immagine incorporata 1]
My project is really heavy, in terms of MB. I'm sure that the size can be
deeply decreased if I'd use just one (or no more than some) picture for all
the emojis. What I mean: one single image that contains all the emojis in a
grid, and the CSS manages to pick the right one and to "cut" all the rest.
Many websites do like that. For example facebook uses this image:
[image: Immagine incorporata 2]
and then let CSS pick the right icon using "background-position: ..." and
"height" & "width".
Maybe there's a way to improve this and, even if you say "i will not try
the CSS technique, since we can't upload Apple emojis on the gnome website
under a GPLv2 license", it could be used with emojione or some other emoji
set.

I would like to suggest a couple of things for your extension:
1- add a customizable shortcut that pops up the extension window
2- the search field should have the focus. I mean: you press the shortcut
-> the window appears -> the search is active already and you can directly
type on it, without the need to click on it first
the previous two suggestions are, I think, extremely userfriendly.
3- write the emoji character wherever the user was typing till then,
bypassing the need to paste it
4- make the window close as soon as the user click on an emoji, but let the
user choose if he wants to activate this feature or not
They're just suggestions, I do not want to force you in any way. You're the
master here :) I sincerely thing these features could make your extension
warmly welcomed and used by a lot of people. :)

One more thing:
[image: Immagine incorporata 3]
Many MANY thanks! ^_^

Jimmy/amivaleo

2017-10-22 1:29 GMT+02:00 Maestroschan <notifications@github.com>:

**Comment by Maestroschan** [comment]
Haha don't be sorry, I am the one who took months before focusing back on this extension ^^

Concerning the research, the search field should currently have the focus with how i did it (i uploaded a beta on github, the "food and drink" icon is not here yet but it works). If it doesn't have the focus, this is a bug :(

I did read how your CSS works, and i think the more realistic thing to try is to display pictures like you did (from emoji one if it works) but only for the dynamic section (where there is recent emojis/search result). But this will be for the next version !

(using one big picture might be lighter, but it's harder to maintain, so i prefer how you did)

> 1- add a customizable shortcut that pops up the extension window

Work in progress, however it's absurdly complex 😫

> 3- write the emoji character wherever the user was typing till then, bypassing the need to paste it

This is planned, but i have no idea if it's possible

**Comment by amivaleo** [comment]
> Haha don't be sorry, I am the one who took months before focusing back on
this extension ^^
You're doing this for free. You don't have to apologize! :)

> try is to display pictures [...] but only for the [...] recent emojis
Why? o.O

> i have no idea if it's possible
I can't help. :(
I wish I could ._.

May I ask you how do you make the settings window? I mean: which software
do you use that produces the files in the "schemas" folder?
Is that Glade...?

Jimmy


2017-10-23 19:07 GMT+02:00 Maestroschan <notifications@github.com>:

**Comment by Maestroschan** [comment]
The XML file is done "manually" with gedit, and compiled with "glib-compile-schemas .", but this is just for the settings keys (it allow the extension to have its own keys in the gsettings database, which you can browse with dconf-editor)

The window itself is made of some Gtk+ widgets, in prefs.js
