### ISSUE TITLE
Use emoji colors

### ISSUE THREAD

**Issue by ronjouch** [Maestroschan/emoji-selector-for-gnome#14]
It would be awesome to have glorious full-color emojis rather than just black&white outlines. Black&white outlines are not only less pretty, they're harder to seek through, as they offer less contrast / differences to the eye.

I don't know if that's technically feasible given GNOME extension constraints :-/ . The [OpenWeather extension](ttps://extensions.gnome.org/extension/750/openweather/) shows colored icons, maybe that can help?

**Comment by Maestroschan** [comment]
On most websites, unicode values are replaced by actual picture files (Emoji One provides a bunch of png and svg files for that). OpenWeather do with actual pictures too.
Having colors is interesting, but need a very different implementation, and is not a priority in my opinion.

**Comment by hrkristian** [comment]
Work done on cairo, pango, gtk3, and fontconfig means gnome-shell now supports color emoji, and by extension so does this extension (heh.)

**Comment by Maestroschan** [comment]
This extension is just using Clutter (or at least St) and CSS: an extension doesn't use GTK +3 (and color emoji are a very recent innovation in GTK+ 3 anyway).
I never said it was technically impossible, it's just that it's not a priority: learning pango, cairo and fontconfig might be very long, and i prefer to focus on things like a search bar, a better interface, more emojis, etc.

**Comment by hrkristian** [comment]
My point was there is no need to keep this open because changes to
underlying libs have now fixed this and we have color emoji support.

**Comment by Maestroschan** [comment]
Ho, ok, i let it open just because if i close it, someone else is going to open a similar issue

**Comment by ronjouch** [comment]
Closing as working for free by GNOME 3.26 native support for color emoji! 🕺👏💪, thanks for the extension @Maestroschan.

![gnome-326-color-emoji-fs8](https://user-images.githubusercontent.com/522085/31303217-caa6294a-aad7-11e7-8d4e-badb637aee40.png)

**Comment by Maestroschan** [comment]
Waw, that's awesome, i need to try it
