### ISSUE TITLE
directly insert emoji

### ISSUE THREAD

**Issue by silberzwiebel** [Maestroschan/emoji-selector-for-gnome#15]
Hi there,

thanks for your extension, I find this easier to use than the "smart" typing feature (typing booster) that can also write emojis.

However, could you add the feature to directly add the clicked emoji in the current text field (and not via the clipboard)? Not sure if this is possible at all.

Many thanks, silberzwiebel

**Comment by Maestroschan** [comment]
If it is possible, i have no idea how :-(

**Comment by Maestroschan** [comment]
it seems impossible, so i'm closing the bug sorry
