### ISSUE TITLE
[idea] tooltips

### ISSUE THREAD

**Issue by Maestroschan** [Maestroschan/emoji-selector-for-gnome#16]
if there is a search entry, users may need to know actual names of emojis

**Comment by amivaleo** [comment]
Not necessarily.
I use "whatsdock" which is a chrome extension that lets me use whatsapp on my laptop. It has support for emoji search.
I do not know any name of any emoji, but if I'm looking for "👍", I write "thumb" and then it's among the results. If I want a specific sad face, I type "sad" and then I get like a dozen of results.

The really hard part of this feature is to write a list of names for each single emoji, and they are like a few thousands... o.o

**Comment by Maestroschan** [comment]
actually, i wrote a huge file with thousand of names and keywords, the problem is that i will never (and no one will never) translate it in any language, because it's too much.
And i often don't have enough vocabulary in english to find the exact emoji i want

**Comment by amivaleo** [comment]
You wrote that in french?
I briefly looked for that but I couldn't find anything. I'm thinking about trying to unpack that chrome extension...

**Comment by Maestroschan** [comment]
no it's in english https://github.com/Maestroschan/emoji-selector-for-gnome/blob/master/emojisCharacters.js
