### ISSUE TITLE
Outdated extension?

### ISSUE THREAD

**Issue by LeeUnd** [Maestroschan/emoji-selector-for-gnome#2]
The link of the gnome.org page says the extension is outdated. Also, when I download it from here and then check it on gnome.org (Installed Extensions) it also shows it as being outdated.

![emoji-selector-outdated-2](https://cloud.githubusercontent.com/assets/5385159/22185354/0601cce2-e0b2-11e6-8a90-13c30a9db976.png)
![emoji-selector-outdated](https://cloud.githubusercontent.com/assets/5385159/22185355/0602fbbc-e0b2-11e6-97f2-c7dc971d0e27.png)

**Comment by Maestroschan** [comment]
Sorry, I did this extension with Debian 8 (Gnome 3.14.4), but only tested it with Arch and Debian 9 (Gnome 3.22.2) : i have no idea how it is actually supported in other versions of Gnome.
Can I ask you what is the version you are using ?

**Comment by LeeUnd** [comment]
Just got the message. I'm using Ubuntu 14.04, Gnome 3.10.4. Thanks

**Comment by Maestroschan** [comment]
I installed ubuntu 14.04 in a VM to do some tests, and the extension just isn't compatible with this old Gnome API, so i will let the .json file (which is responsable of the "outdated" message) as it is : without the "3.10" version.
