### ISSUE TITLE
Cannot change keyboard shortcut

### ISSUE THREAD

**Issue by matuskropuch** [Maestroschan/emoji-selector-for-gnome#23]
There is an option in the settings but I can just turn on/off if I want to use keyboard shortcut to toggle the menu, but cannot change the shortcut itself. It is just greyed out with the apply button. I don't know if this is a bug or the feature itself isn't implemented yet but would be nice to have.

**Comment by Maestroschan** [comment]
it's not an actual bug, i just didn't code the "change shortcut" feature yet.

You can change manually it via dconf-editor at /org/gnome/shell/extensions/emoji-selector/emoji-keybinding
