### ISSUE TITLE
Support picking a series of emojis

### ISSUE THREAD

**Issue by ronjouch** [Maestroschan/emoji-selector-for-gnome#24]
It would be awesome to be able to select (and copy to clipboard) multiple emojis in one shot.

Currently, when clicking an emoji, the selector is closed and the emoji is copied to clipboard.

What if, when holding `Ctrl` or `Shift` and clicking an emoji, the selector remained open, letting the user pick one or several additional emojis, which would all be copied concatenated to clipboard only when the selector is dismissed? (on first click out of the Shell panel)

That's the behavior of selecting emojis on iOS/Android, which live in their own keyboard, and this emoji keyboard is not dismissed on first emoji pick, it stays active, enabling picking a series of emojis (for example, 👍👌🤝).

---

Nit: I'm not sure how feasible this is with the GNOME Shell extensions API:

1. Not sure it's feasible to prevent closing the panel on click
2. Not sure it's feasible to set up an event handler on clicking out of the Shell panel (in web events terminology, `onblur`)

... but a more implementation-friendly workflow can probably be imagined within Shell Extension constraints?

**Comment by Maestroschan** [comment]
There is not an actual well-defined "extensions API", it's mainly monkey-patching of the existing GNOME Shell code.
I will try to do that next month, it seems feasible

**Comment by ronjouch** [comment]
@Maestroschan yeah, well, congrats and thanks to you to work within this monkey-patching 🙂. Makes me think of [Shell bug #788931](https://bugzilla.gnome.org/show_bug.cgi?id=788931), in which extensions were able to crash Shell 😄. Also maybe of interest to you, the current plan for extensions-backwards-incompatible [Shell 4](https://wiki.gnome.org/Initiatives/Wayland/GnomeShell/GnomeShell4).

**Comment by Maestroschan** [comment]
I didn't know there was an open bug for that, a very similar issue is bothering me for the "appfolder manager" extension

**Comment by Maestroschan** [comment]
Finally done, i'll upload here tomorrow
