### ISSUE TITLE
Emoji Search -> empty spaces can be clicked

### ISSUE THREAD

**Issue by amivaleo** [Maestroschan/emoji-selector-for-gnome#25]
Hi!

Sorry for the bad title.
I noticed that, if you search for an emoji (let's say you type "mad"), you can click on the empty spaces (the red circled area in the picture): 
![schermata da 2017-12-18 15-16-47](https://user-images.githubusercontent.com/24316547/34110499-25e2c2ba-e407-11e7-833a-c0c49f9506a4.png)

Can this be avoided that?

**Comment by Maestroschan** [comment]
Yes it can be avoided, i'll do it later (it has always been like this, but empty buttons were very small, now with the new CSS they have the same size as others)
