### ISSUE TITLE
Extension breaks xorg session

### ISSUE THREAD

**Issue by vredesbyyrd** [Maestroschan/emoji-selector-for-gnome#26]
Okay. This is a strange one that i really cant figure out. I started a wayland session for the first time to see how development is coming along (gnome 3.26.2 / arch). After playing around a little but not changing anything, i logged out of wayland and tried to start a xorg session (via gdm), and it just froze at the speckled gdm screen with the cursor. This started a 5 hour troubleshooting headache, trying to narrow down the cause. I attempted to startx using xinit file to get more output on what was happening, but ultimately the output proved not helpful. And xorg.logs didnt show anything out of the ordinary that i can tell. From the output at startx, the best i could tell it appeared like xorg was borked somehow. So i was troubleshooting from that angle with no luck. My next approach was disabling extensions one by one in wayland, then trying to start a xorg session. This narrowed it down to emoji-selector. I then tried to reinstall the extension but that didnt change anything. As long as its activated, i cannot start a xorg session. One last thing to note, no matter how i uninstall the extension, my 'most used' emojis always remain at the top after i reinstall. So it appears some sort of user-data/cache is left behind. I cant find where that data is stored. Maybe that is causing problems? I am at a loss. I know basically nothing about wayland and how it interacts with separate xorg session, so i am having trouble getting a handle on whats wrong. Any ideas would be appreciated. 

Edit: I have tried using both the arch package installed system wide and installing locally from the gnome-extension website. Doesnt change anything

**Comment by Maestroschan** [comment]
Since loading all emojis' pictures (plus all research keywords) is kinda massive, i'm not really surprised it could cause issues.
When there was no support for color emojis, it was really quicker and lighter, i guess your system can't load it (but why only with Xorg ? idk, it's an extension i developped with Debian/Xorg and it's slow to load but it works).

Concerning recent emojis, it's really lame: this is a feature i introduced when i began to do extensions, and i didn't know how to store these emojis, so i put them... in a setting key. You can delete it using the gsettings command if you know how it works, or using dconf-editor at /org/gnome/shell/extensions/emoji-selector/ (disable the extension before deleting it, the default value should be '😂,❤️,😍,😭,😊,😒,😘,😩,🤔,☺️,👌,😔,😏,😁,😉,👍,😱,😳,😎,👀,💩,' and then it displays penguins). I suggest to delete every key there, so it will restore default configuration.

**Comment by vredesbyyrd** [comment]
Thanks for getting back so quick. I feel like an idiot for not looking for the dconf keys. Spaced that one out i guess. 

So I deleted the keys then re-enabled the extension (from xorg). logged out and tried to log back in, but still could not log into a xorg session. So i disabled it from wayland. I should clarify, I had 0 problems until i tested out wayland. I was using the extension with xorg no problem for a week, could log into xorg with no issues. It all started once i tried wayland for five minutes. So it seems like something got screwed by wayland but its proved basically impossible to narrow down. Or beyond me i suppose. Im tempted to nuke my entire install from orbit and reinstall. Because if i have this issue, what else could be going on that i just haven't ran into yet? Uhg. This entire charade makes me very wary of wayland now. I mean literally all i did was log into wayland, open my browser and a few apps, then try to log back into xorg. Makes no sense. 

ps, sorry for the blunt title. Maybe this is more of a wayland bug than anything, because like i said i had zero issues before I tried to take wayland for a test drive.

**Comment by Maestroschan** [comment]
I may not be the person who will fix this bug, but it's still very useful for me to know what's going on with emoji support outside of my Debian.

Can you, for example, paste emojis in the GS search entry or in the run dialog ?
Or, if you have a clipboard manager, does it display copied emojis ?

**Comment by vredesbyyrd** [comment]
For sure, i understand. 

The extension runs perfectly fine if i enable it once i am logged into gnome/xorg. So yes i can copy/paste. I mostly use it along with the gsconnect extension.

**Comment by vredesbyyrd** [comment]
So after a little more testing, and a newly installed root partition, i am moderately confident that this is an issue with xorg-server itself, on arch at least. There is a bug report for arch that broadly relates to xserver freezing at startup. I only have that freeze when this extension is activated, but i think it might be related. We shall see if it resolves itself in the future. I startx via command line and fish shell, so my current solution is setting an alias for easily enabling and disabling the emoji extension, either emoji-e or emoji-d. That way if i forget to disable it before shutting down my computer, i can easily disable it before starting x. Because like i said before, the extension runs 100% fine if its enabled post logging in. Good enough for me.

**Comment by Maestroschan** [comment]
Ok, if there are other people with a similar bug, i will try to add a little delay before actual activation

**Comment by vredesbyyrd** [comment]
Could be a good solution if others run into the same thing. Thanks.

**Comment by twaugh** [comment]
I am seeing something very similar. On Fedora 27 using Xorg for my log-in display, when this extension is already enabled I very often (most of the time) find that although gnome-shell has started I do not see my desktop, only the grey speckle. The mouse cursor will move, and I can switch VTs etc. It is not every single time, but most times.

I disabled all the extensions I use and restarted, and it worked fine. Then I re-enabled them one-by-one, restarting twice to test, until it failed again. I now have everything enabled again except for this plugin, and logging in works fine.

**Comment by vredesbyyrd** [comment]
Okay. So the issue is not limited to Arch based distros. Does not effect wayland, only xorg.

I have not dug into it further myself. I just made an alias so i can enable it quickly post login/disable at login shell. I dont shutdown my laptop often so its a good enough workaround for my usage until the core issue is found and resolved. 

I thought maybe it had something to do with loading large color images, so i tried it with just b+w, but that didn't make a difference.

**Comment by Shnoulle** [comment]
I'm on Fedora Gnome Version 3.26.2. I use Gnome Xorg and not Wayland due to some issue with Wayand and my video card.

And i have exactly the same issue:

1. Activate extension after gnome start : OK
2. Start with extension activated : gnome-shell goes at 130% again and again
3. Try with Gnome classic : same issue

I'm unsure it totally related to this extension, but disable it : and gnome start again.

**Comment by Maestroschan** [comment]
Since i couldn't reproduce this bug,  could you test if my last commit has a positive effect on this issue ?

**Comment by vredesbyyrd** [comment]
Just tested the latest commit and everything seems to be in working order now. I cloned the repo and installed manually, since im not sure the latest commit made it to extension site yet. 

I tried starting gnome on xorg 3 times all with no issues. Xorg session starts up very quickly. So atleast for me, i can say the issue appears resolved. 

Thanks for all your work.

**Comment by Maestroschan** [comment]
>since im not sure the latest commit made it to extension site yet.

[Haha](https://i.imgur.com/hgylkh6.png)

`*`some tumbleweeds cross the gnome website`*`
