### ISSUE TITLE
Extension makes screen unlock slower

### ISSUE THREAD

**Issue by BHSPitMonkey** [Maestroschan/emoji-selector-for-gnome#29]
Having this extension enabled seems to add an extra second or two when unlocking GNOME. Anything we can do to reduce the performance hit when the screen is unlocked? (I'm guessing some objects are re-rendered/re-initialized each time the GNOME shell reappears, and maybe some of this could be cached within the extension to avoid repeating work).

**Comment by Maestroschan** [comment]
This has already been fix a month ago, but extensions.gnome.org didn't approve it yet (gnome reviewers likely hibernate since december).

Did you try a manual installation of the most recent version ? (see the readme file)

**Comment by BHSPitMonkey** [comment]
Great to hear, I actually hadn't tried installing from master yet. I'm actually not yet on a version of GNOME with color emoji support or fonts, so I was feeling the delay even with the monochrome glyphs.

Closing this!
