### ISSUE TITLE
Improve the UI by displaying multiple columns of emoji

### ISSUE THREAD

**Issue by keeferrourke** [Maestroschan/emoji-selector-for-gnome#3]
Awesome idea! I found this extension after it was featured on OMG! Ubuntu, but I have a few complaints.

The current interface makes very little sense. Scrolling through a massive list of emoji displayed in a single column list isn't very user friendly. It would be better if you could display the emoji in a grid format, similar to the EmojiOne browser extension:

![screenshot from 2017-01-28 20-02-12](https://cloud.githubusercontent.com/assets/6888381/22401074/f1ea51f6-e594-11e6-8feb-af2098181338.png)

**Comment by Maestroschan** [comment]
A grid was my original plan, but i'm a beginner, so i did with a simple list as a first version.
Since the present interface is an ergonomic heresy, i think it will be corrected in the next version

**Comment by Maestroschan** [comment]
It's done, i will upload it on the website
