### ISSUE TITLE
Extension crashes Shell with settings schema error

### ISSUE THREAD

**Issue by ronjouch** [Maestroschan/emoji-selector-for-gnome#36]
Hi. I Installed 737fb4b885f8df406f389723efa20e384e04af68, but it crashes Shell with

```
May 06 16:00:03 t gnome-shell[1058]: Settings schema 'org.gnome.shell.extensions.emoji-selector' does not contain a key named 'gender'
```

I see the `schemas` folder ships a `gschemas.compiled`, and I tried re-creating it:

```bash
> gnome-shell --version
GNOME Shell 3.28.1
> cd /home/ronj/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/schemas
> rm gschemas.compiled
> glib-compile-schemas /home/ronj/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/schemas
> ls -la gschemas.compiled
-rw-r--r-- 1 ronj ronj 792 May  6 16:03 gschemas.compiled

```

, but I still get the same crash. What am I missing? An addition to the Installation section of README would be great 🙂.

**Comment by Maestroschan** [comment]
if you're trying to install the development version from here, it's possible that i just forgot to add the schemas files to the last commit

**Comment by Maestroschan** [comment]
try it now ?

**Comment by ronjouch** [comment]
Works! Thanks 👍.
