### ISSUE TITLE
Hiding the tray icon

### ISSUE THREAD

**Issue by goncalossilva** [Maestroschan/emoji-selector-for-gnome#37]
I use Emoji Selector purely with the keyboard. The workflow always goes like this:
* Press the shortcut
* Search for the emoji
* Navigate to it (btw this is pretty hard as there's no highlight of what is focused and I have to count)
* Enter to copy

Given this workflow, having the tray icon visible at all times is unnecessary and distracting.

Would it be possible to add an option to hide it and only show once the shortcut is used? This would finally move me off ibus' somewhat ugly Emoji Choice permanently. Thanks!

**Comment by Maestroschan** [comment]
Great idea, fluent to use, thanks for the feedback

**Comment by goncalossilva** [comment]
Thanks for the uber fast response. Amazing to see this in! :heart_eyes:
