### ISSUE TITLE
Remove the "back" button

### ISSUE THREAD

**Issue by amivaleo** [Maestroschan/emoji-selector-for-gnome#41]
Hi ~~Maestro~~ Romain 😉 !

I was wondering: why do we have a back button (the first left-arrow button) instead of using the category buttons for toggling the emoji list?

Let me say that in other words, using an example:
I click on the "flag" button -> the flag list shows up -> I click again on the "flag" button -> the list gets hidden.

To me, that back button is unnecessary and a bit "counterintuitive" in some sense.

Let me know what you think about this. :)

**Comment by Maestroschan** [comment]
It makes sense

**Comment by amivaleo** [comment]
Not much of a talker, are you? :D

**Comment by Maestroschan** [comment]
When i totally agree i prefer to code instead of discussing 😄

**Comment by amivaleo** [comment]
You know, I really feel honored for being able to propose something that you like. ^_^

Thank you.
