### ISSUE TITLE
Error when loading preferences

### ISSUE THREAD

**Issue by picsi** [Maestroschan/emoji-selector-for-gnome#8]
On Arch, GNOME 3.24:

![captura de tela de 2017-04-29 19-01-25](https://cloud.githubusercontent.com/assets/23157217/25559344/7baee56c-2d0e-11e7-83e1-9db699950e96.png)

**Comment by Maestroschan** [comment]
Is it the version from extensions.gnome.org, or from the github repo ?

**Comment by picsi** [comment]
>This version is from extensions.gnome.org i guess ?

Correct! Is it difficult/takes too long to update the extensions.gnome.org version? It seems easier to maintain and update your extension this way :)

**Comment by Maestroschan** [comment]
> Is it difficult/takes too long for you to update the extensions.gnome.org version?

No, I was trying to add some new features, i finished it yesterday and i just uploaded the new release on both github and the GNOME website an hour ago.

On the GNOME website, the new version still needs to be reviewed and approved by moderators, so i can't tell when it will be released (maybe tuesday ? wednesday ?)

**Comment by Maestroschan** [comment]
furthermore, i see you speak portuguese : i always let the .pot and all .po files in the "locale" folder, if you know how to do, feel free to contribute to translation ;)

**Comment by picsi** [comment]
See https://github.com/Maestroschan/emoji-selector-for-gnome/pull/9

**Comment by Maestroschan** [comment]
Thank you !

**Comment by Maestroschan** [comment]
A new version has been yesterday (your translations are not in this version, it will be the next), did this update solve the initial issue ?

**Comment by picsi** [comment]
It did solve the issue. Thanks! :)
